prefixes:
  "documentation/": REQ
  "documentation/notes/": NOTE
  "documentation/notes/ideas.md": IDEA
  "documentation/references/": REF
  "documentation/specifications/": SPEC
  "documentation/work-items/": WORK
